[[pciutils]]
arch = "aarch64"
git-tree-sha1 = "b50352fc0c0a0625517687ea93545425f2eb7c20"
libc = "glibc"
os = "linux"

    [[pciutils.download]]
    sha256 = "fd710063428aabb5688062189f0443c577cd82b22f42ed892a9cfce124786119"
    url = "https://github.com/JuliaBinaryWrappers/pciutils_jll.jl/releases/download/pciutils-v3.7.0+1/pciutils.v3.7.0.aarch64-linux-gnu.tar.gz"
[[pciutils]]
arch = "aarch64"
git-tree-sha1 = "824df2239c8e18eb85135419fa03b143589d5a83"
libc = "musl"
os = "linux"

    [[pciutils.download]]
    sha256 = "fe76008b31872b455c03818459739d985ea3f17d5e40f78d6668bde6e0b6f8f2"
    url = "https://github.com/JuliaBinaryWrappers/pciutils_jll.jl/releases/download/pciutils-v3.7.0+1/pciutils.v3.7.0.aarch64-linux-musl.tar.gz"
[[pciutils]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b1d459d86e24c71fed226a19d2ad4f3f8a7dd885"
libc = "glibc"
os = "linux"

    [[pciutils.download]]
    sha256 = "63a421cc4a67b1b4fa98429f3fd6ffdb04b0db7828d3e27f4c229374771c273c"
    url = "https://github.com/JuliaBinaryWrappers/pciutils_jll.jl/releases/download/pciutils-v3.7.0+1/pciutils.v3.7.0.armv6l-linux-gnueabihf.tar.gz"
[[pciutils]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ed693702f57f3dcf5267029e48d1ffba3cfd4227"
libc = "musl"
os = "linux"

    [[pciutils.download]]
    sha256 = "7eb0678a3dc078d9aad0c1cf5ad00ed861c7723e00cfe3921e3324a85255f059"
    url = "https://github.com/JuliaBinaryWrappers/pciutils_jll.jl/releases/download/pciutils-v3.7.0+1/pciutils.v3.7.0.armv6l-linux-musleabihf.tar.gz"
[[pciutils]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "20210b6b369d1289277521eb34f780cefda8dd85"
libc = "glibc"
os = "linux"

    [[pciutils.download]]
    sha256 = "6fb28e1a7b71989ac3374f8d7914cca7f1edc46af81b062041c2c776775a8893"
    url = "https://github.com/JuliaBinaryWrappers/pciutils_jll.jl/releases/download/pciutils-v3.7.0+1/pciutils.v3.7.0.armv7l-linux-gnueabihf.tar.gz"
[[pciutils]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "41f7a2227b7ac53aaa44fcffb83ef65fe798dca7"
libc = "musl"
os = "linux"

    [[pciutils.download]]
    sha256 = "0e7410325fc0fa67b75998441549f57b4d1f82f595f9b5177bf21e37a15de83b"
    url = "https://github.com/JuliaBinaryWrappers/pciutils_jll.jl/releases/download/pciutils-v3.7.0+1/pciutils.v3.7.0.armv7l-linux-musleabihf.tar.gz"
[[pciutils]]
arch = "i686"
git-tree-sha1 = "73524b86af9f9748a2417319dbe7eb837bbec79a"
libc = "glibc"
os = "linux"

    [[pciutils.download]]
    sha256 = "a8ed87d9cb07c9d4a38e477326ad6dabd03deec48f2508b39fb084c94af1c46f"
    url = "https://github.com/JuliaBinaryWrappers/pciutils_jll.jl/releases/download/pciutils-v3.7.0+1/pciutils.v3.7.0.i686-linux-gnu.tar.gz"
[[pciutils]]
arch = "i686"
git-tree-sha1 = "ccdccc4bf072dedfe179be63c29a718b16dc95dc"
libc = "musl"
os = "linux"

    [[pciutils.download]]
    sha256 = "67c8acecf3651da09b8a10e766ef98f3a90afc5605eba127a5e24043dd29babc"
    url = "https://github.com/JuliaBinaryWrappers/pciutils_jll.jl/releases/download/pciutils-v3.7.0+1/pciutils.v3.7.0.i686-linux-musl.tar.gz"
[[pciutils]]
arch = "powerpc64le"
git-tree-sha1 = "bcddc3667ed3980c00a01017376cc66fac8d4d13"
libc = "glibc"
os = "linux"

    [[pciutils.download]]
    sha256 = "4069feb36511590cae0d833b68bfcb8bdb5baacbd648586d16e8d0300d1275f1"
    url = "https://github.com/JuliaBinaryWrappers/pciutils_jll.jl/releases/download/pciutils-v3.7.0+1/pciutils.v3.7.0.powerpc64le-linux-gnu.tar.gz"
[[pciutils]]
arch = "x86_64"
git-tree-sha1 = "f76fdfc6b1e18f0ac887ce10c7d7147d79c60032"
libc = "glibc"
os = "linux"

    [[pciutils.download]]
    sha256 = "eca7c5c30ea43db6e6348faa60923276779ea4bf741b1baeb2d9dc7fa9ae840e"
    url = "https://github.com/JuliaBinaryWrappers/pciutils_jll.jl/releases/download/pciutils-v3.7.0+1/pciutils.v3.7.0.x86_64-linux-gnu.tar.gz"
[[pciutils]]
arch = "x86_64"
git-tree-sha1 = "804eee41c65bbee29feca0d883f890b5d3bafee0"
libc = "musl"
os = "linux"

    [[pciutils.download]]
    sha256 = "380c261b978f529dc8f3ba28995516d13916bbc3160ddf2b63e7041ad3cf2662"
    url = "https://github.com/JuliaBinaryWrappers/pciutils_jll.jl/releases/download/pciutils-v3.7.0+1/pciutils.v3.7.0.x86_64-linux-musl.tar.gz"
[[pciutils]]
arch = "x86_64"
git-tree-sha1 = "649267cf4be8212dcd19840f4c5b2c6b3c0a4471"
os = "freebsd"

    [[pciutils.download]]
    sha256 = "b8ad9ace877c6def815ca48b0fcb63143178f2d26228a2d7e18b7a74e17fbc25"
    url = "https://github.com/JuliaBinaryWrappers/pciutils_jll.jl/releases/download/pciutils-v3.7.0+1/pciutils.v3.7.0.x86_64-unknown-freebsd.tar.gz"
